### ISSUE TITLE
contributorRole/creatorRole links to deprecated controlled vocab

### ISSUE THREAD

**Issue by mcampos-quinn** [WGBH/PBCore_2.1#38]
The pages for [`<creatorRole>`](http://v3.pbcore.org/pbcorecreator/creatorRole/) and [`<contributorRole>`](http://pbcore.org/pbcorecontributor/contributorrole/) link to [deprecated](http://metadataregistry.org/concept/list/page/1/vocabulary_id/128.html) controlled [vocabulary](http://metadataregistry.org/concept/list/vocabulary_id/127.html) lists.

They could both link to the current [list](http://metadataregistry.org/concept/list/vocabulary_id/460.html) that covers both tags?

Related to this, the examples show links to deprecated values.

**Comment by rfraimow** [comment]
Thank you for catching this issue! We've made the quick fix on the link, but please be aware that we're currently in the process of re-launching the website now, so examples and page layouts will change in the near future.

**Comment by mcampos-quinn** [comment]
Awesome, thanks!
